# Generated by Django 4.2.8 on 2023-12-14 08:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("resources", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dayavailability",
            options={
                "ordering": ("day",),
                "verbose_name": "availability",
                "verbose_name_plural": "availabilities",
            },
        ),
        migrations.AlterModelOptions(
            name="resource",
            options={
                "ordering": ("start_date",),
                "verbose_name": "resource",
                "verbose_name_plural": "resources",
            },
        ),
    ]
