# Generated by Django 4.2.8 on 2023-12-13 18:29

import django.utils.timezone
from django.db import migrations, models

import users.models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="phone",
        ),
        migrations.AddField(
            model_name="user",
            name="jwt_token_key",
            field=models.CharField(
                default=users.models.generate_jwt_token, max_length=12
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="time_zone",
            field=models.DateTimeField(
                blank=True, default=django.utils.timezone.now, verbose_name="time zone"
            ),
        ),
    ]
